### ISSUE TITLE
Error: 'module' object has no attribute 'SamtoolsDispatcher'

### ISSUE THREAD

**Issue by qins** [umich-brcf-bioinf/AmpliconSoftClipper#1]
Error: 'module' object has no attribute 'SamtoolsDispatcher' while `pysam                     0.10.0`

`python katana-runner.py examples/primers.txt examples/chr22.bam examples/chr22_output.bam`

> 2017/04/18 09:26:39|Reading primer pairs from [examples/primers.txt]
2017/04/18 09:26:39|Read [534] primer pairs
2017/04/18 09:26:39|Building transformations from BAM [examples/chr22.bam]
2017/04/18 09:26:44|Built transforms for [73823] alignments
2017/04/18 09:26:44|Writing transformed alignments to [examples/chr22_output.bam]
2017/04/18 09:26:49|PRIMER_STATS|chrom|target_id|sense_start|sense_count|antisense_count|sense_percent
2017/04/18 09:26:49|PRIMER_STATS|.|PRIMER_NOT_RECOGNIZED|0|3799|3684|50
2017/04/18 09:26:49|PRIMER_STATS|chr22|SMARCB1_1_AS_ver3|24133942|7606|8887|46
2017/04/18 09:26:49|PRIMER_STATS|chr22|SMARCB1_2_ver3|24143085|3779|2525|59
2017/04/18 09:26:49|PRIMER_STATS|chr22|SMARCB1_3_AS_ver3|24145553|6197|6183|50
2017/04/18 09:26:49|PRIMER_STATS|chr22|SMARCB1_4_ver3|24176246|3319|3331|49
2017/04/18 09:26:49|PRIMER_STATS|chr22|CACNA1I_S728L|40054829|8138|8126|50
2017/04/18 09:26:49|PRIMER_STATS|chr22|CACNA1I_A1030S|40058073|4155|4094|50
2017/04/18 09:26:49|EXCLUDE|7433 alignments were excluded because: UNMATCHED_PRIMER_PAIR
2017/04/18 09:26:49|EXCLUDE|1 alignments were excluded because: INVALID_CIGAR
2017/04/18 09:26:49|EXCLUDE|114 alignments were excluded because: UNMAPPED_ALIGNMENT
2017/04/18 09:26:49|WRITE_BAM|sorting BAM
2017/04/18 09:26:49|ERROR: An unexpected error occurred
2017/04/18 09:26:49|Traceback (most recent call last):
  File "/test_katana/Katana/katana/clipper.py", line 227, in main
    _handle_reads(handlers, read_iter, read_transformations)
  File "/test_katana/Katana/katana/clipper.py", line 135, in _handle_reads
    handler.end()
  File "/test/test_katana/Katana/katana/readhandler.py", line 128, in end
    pysam_sort(self._tmp_bam_filename, output_root)
  File "/test/test_katana/Katana/katana/readhandler.py", line 19, in pysam_sort
    pysam.SamtoolsDispatcher("sort", None).__call__(input_filename,
AttributeError: 'module' object has no attribute 'SamtoolsDispatcher'

**Comment by cgates** [comment]
Thanks for your interest in Katana; we're sorry you're having trouble.

Katana was tested with pysam versions 0.8.3 and 0.8.4; pysam has since changed their code and we have not yet had a chance to update Katana accordingly.  As a workaround, if you create a virtual environment/conda environment, you can install one of the older version of pysam and Katana should work better.

Hope this helps.
Best,
cg
