### ISSUE TITLE
primer file primer.txt is not identical with the description in Readme.

### ISSUE THREAD

**Issue by qins** [umich-brcf-bioinf/AmpliconSoftClipper#2]
Only the fields in readme description are necessary? Or we should make our primer file just like the example Primer.txt?

And "Sense Sequence Tailed Illumina" tailed with "**CGCTCTTCCGATCT**CTG", as much as I know the regular adapter end with  **CGCTCTTCCGATCT**, could you explain a bit? Thanks.

Primer.txt's header:
> id      Customer TargetID       Primer Set      Chr     Original Target Start   Original Target End     Converted Target End  Converted Target Start  Genome Build    Sense Start     Antisense Start Sense Sequence  Antisense Sequence   Sense Sequence Tailed Illumina   Antisense Sequence Tailed Illumina

while description in Readme:
> primer file is tab separated; the header line includes the following fields:
> Customer TargetID
> Chr
> Sense Start
> Antisense Start
> Sense Sequence
> Antisense Sequence

**Comment by pabsju** [comment]
Hello, only the fields in the Readme should be necessary. The additional fields present in the example primers.txt file such as "Sense Sequence Tailed Illumina" are not necessary and are not used by Katana. The primer.txt file included in the examples folder was derived from an earlier manifest file, and we simply retained the superfluous columns. Apologies for any confusion.

**Comment by qins** [comment]
Got it. Thank you!
