### ISSUE TITLE
Errors in BAM files after soft-clipping primers

### ISSUE THREAD

**Issue by garrulus-glandarius** [umich-brcf-bioinf/AmpliconSoftClipper#4]
Hi, thanks for the tool!

I've used the following command to soft-clip primers:
```sudo katana /media/sf_Desktop/TSCA_documents/katana_my_primers.txt /media/sf_Desktop/170303_M04607_0037_000000000-AR7YC/BAM/bam/test.bam test.clipped.bam```

I've run Picard's ValidateSamFile before and after primer clipping. BAM files were free of errors before running Katana but ValidateSamFile revealed errors in the clipped files:

_HISTOGRAM java.lang.String Error Type Count_

_ERROR:INVALID_UNALIGNED_MATE_START 54543_

_ERROR:MISMATCH_MATE_CIGAR_STRING 2146704_

I've [observed ](https://www.biostars.org/p/279503/)the same outcome of soft-clipping using BamClipper. Is this an expected outcome of soft-clipping primer sequences? How to handle it?

**Comment by cgates** [comment]
Thank you for your interest in Katana!

In paired end, the start position of a read is stored in the read and also in the read's mate. When Katana soft-clips the end of the read, it is supposed to make a coordinated change to both reads; based on your results, I suspect that (for unknown reasons) it didn't correctly update the mate's start position. So, the behavior you've illustrated is not ideal and I suspect it is a bug in the Katana tool. If you were willing to share your inputs, we could reproduce the behavior on our end and try to understand the nature of the problem. If that's interesting, send us an email at 
bfx-katana@umich.edu
and we can coordinate a way to get those files.

In the interim, you might try running Picard tool FixMateInformation (and then rerunValidateSamFile). FixMateInformation attempts to reset the mate start position and clean up other "clerical" anomalies in the BAM.

Best,
Chris Gates

**Comment by cgates** [comment]
FYI, these problems were resolved in the 0.1.2 release on 11/2/2017.

**Comment by garrulus-glandarius** [comment]
Thank you so much for your kind support! I've tried the new release and it works perfect!
